export { default as digittallyPage } from './digit-tally page.png';
export { default as digittallyPage2 } from './digit-tally page2.png';
export { default as digittallyPage3 } from './digit-tally page3.png';
export { default as digittallyApp } from './digit-tally app.png';
export { default as digittallyApp2 } from './digit-tally app2.png';
export { default as digittallyApp3 } from './digit-tally app3.png';
export { default as digittallyApp4 } from './digit-tally app4.png';
export { default as digittallyApp5 } from './digit-tally app5.png';
export { default as digittallyApp6 } from './digit-tally app6.png';
export { default as digittallyApp7 } from './digit-tally app7.png';
export { default as timesheet1 } from './timesheet1.png';
export { default as timesheet2 } from './timesheet2.png';
export { default as timesheet3 } from './timesheet3.png';
export { default as timesheet4 } from './timesheet4.png';
export { default as timesheet5 } from './timesheet5.png';
export { default as timesheet6 } from './timesheet6.png';
export { default as timesheet7 } from './timesheet7.png';
export { default as timesheet8 } from './timesheet8.png';
export { default as candourLogo } from './candour.png';
